block/blk-core.c
block/blk-sysfs.c
block/blk-throttle.c
include/linux/blkdev.h
include/linux/genhd.h

Kernel now supports cgroup bps and iops hard limit by io-throttling.
But that's not a scalable way, because block devices' bandwith is
always changing over time.
This patch dynamically adjusts bps limit of each blkio cgroup according
to its pre-set weight. Additionally, if a process has not issued any io
request during a time window, its weight will be shared by other processes
until its next io request.
Signed-off-by: Lei Chen <lennychen@tencent.com>

cgroup: blkio: adjust block io bps limit by weight

---

arch/sh/boards/mach-landisk/irq.c

Note that the word 'swtich' is wrong,
so that 'swtich' should been replaced with 'switch'.

Fixed typo: 'swtich' in irq.c

---

arch/arm/vfp/vfpmodule.c

Fixed macro  spelling error: THREAD_NOFTIFY_SWTICH -> THREAD_NOFTIFY_SWITCH

Fixed macro spelling mistake in vfpmodule.c

---

arch/x86/kernel/cpu/amd.c
arch/x86/kernel/cpu/cacheinfo.c

In patch 660998b7a96884a6fb11513e561fb2934718096a, merged codes in
function amd_get_topology() not works for Hygon Family 18h.
Move Hygon CPU socket ID calculation codes to cacheinfo_amd_init_llc_id()
function,to make Socket ID calculate codes works for Hygon Family 18h CPU.

x86/cpu: Fix Hygon Family 18h socket ID calculate issue

---

Documentation/networking/ipvs-sysctl.txt
include/net/ip_vs.h
net/netfilter/ipvs/ip_vs_core.c
net/netfilter/ipvs/ip_vs_ctl.c

Since 'commit f719e3754ee2 ("ipvs: drop first packet to
redirect conntrack")', when a new TCP connection meet
the conditions that need reschedule, the first syn packet
is dropped, this cause one second latency for the new
connection, more discussion about this problem can easy
search from google, such as:
1)One second connection delay in masque
https://marc.info/?t=151683118100004&r=1&w=2
2)IPVS low throughput #70747
https://github.com/kubernetes/kubernetes/issues/70747
3)Apache Bench can fill up ipvs service proxy in seconds #544
https://github.com/cloudnativelabs/kube-router/issues/544
4)Additional 1s latency in `host -> service IP -> pod`
https://github.com/kubernetes/kubernetes/issues/90854
5)kube-proxy ipvs conn_reuse_mode setting causes errors
with high load from single client …

ipvs: avoid drop first packet by reusing conntrack

---

include/net/ip_vs.h
net/netfilter/ipvs/ip_vs_bpf_proc.c
net/netfilter/ipvs/ip_vs_conn.c

previously, for clusterIP type service, no SNAT is done.
However, in some case, user may add rs ip outside vpc which may require
SNAT.
To address this issue, a non snat ip table of max 64 entries are added.
Usage:
1. echo -n "0.0.0.0/0" > /proc/net/ip_vs_non_masq_cidrs will make all ip
bypass snat.
2. echo -n ":" > /proc/net/ip_vs_non_masq_cidrs will make all ip do snat.
3. echo "a.b.c.d/24:a.b.c.e/24" >  /proc/net/ip_vs_non_masq_cidrs
Test case:
create a cluster with 9 PODS
172.19.0.175  172.19.0.176   172.19.0.177 172.19.0.241 172.19.0.242
172.19.0.243 172.19.0.244 172.19.0.100  172.19.0.101
0)
/proc/net/ip_vs_non_masq_cidrs is empty, curl cluster ip shall do SNAT
result: pass
1)
Three ip/32 in  /proc/net/ip_vs_non_masq_cidrs
echo "172.19.0.175/32:172.19.0.176/32:172.19.0.177/32" > …

ipvs-ebpf: add non-masqurade-agent support.

---

block/blk-wbt.c
fs/ext4/ext4.h
fs/ext4/extents.c
fs/ext4/file.c
fs/ext4/inode.c
fs/ext4/ioctl.c
fs/ext4/mballoc.c
fs/ext4/mballoc.h
fs/ext4/move_extent.c
fs/ext4/super.c
fs/ext4/sysfs.c
fs/ext4/xattr.c
fs/overlayfs/copy_up.c
include/trace/events/ext4.h

Fix some problems of ext4:
1. In the scenario of writing sparse files, the Per-inode prealloc list may be very long, resulting in high overhead for ext4_mb_use_preallocated(). To circumvent this problem, we limit the maximum length of per-inode prealloc list to 512 and allow users to modify it.
2. We can't pass error pointers to brelse().
Fix some problems of wbt:
1. At present, wbt's wake-up mechanism for wait_queue can induce thundering herd issue and intense lock competition. In the
context of ipi, this may induce hard lockup.
Fix some problems of overlay:
1. Fix copy-up failed due to NFSv4-ACL not support

Fix some problems of ext4, overlay, wbt

---

kernel/sysctl.c
mm/memcontrol.c

Without preemption, if syscall excutes too long it will significantly
affect performance of other important processes. So add a shceduling
point when showing root memcg usage.
Signed-off-by: yongduan <yongduan@tencent.com>
Signed-off-by: charliecgxu <charliecgxu@tencent.com>

memcg: add scheduling point while showing memcg usage

---

kernel/softirq.c
kernel/sysctl.c

Enhance network tail latency by directly handling softirq
when detecting long scheduling latency of ksoftirqd.
Signed-off-by: yongduan <yongduan@tencent.com>
Signed-off-by: charliecgxu <charliecgxu@tencent.com>

softirq: enhance network latency

---

net/netfilter/ipvs/ip_vs_xmit.c

reason: in ipvs_mode ==1 , skb_rtable is ip_vs_nat_xmit is null.
Test case: test bpf mode nodeport ok!
Signed-off-by: jianmingfan <jianmingfan@tencent.com>

fix regression bug cause by ipvs_mode=2 patch

---

include/linux/smp.h
kernel/smp.c
kernel/sysctl.c
net/core/dev.c

网络rps发送IPI中断给其他核，是一个一个发送IPI中断的，在虚拟化场景下每发送一个IPI都会导致一次退出。
虚拟化场景使用pvipi来优化退出次数，通过hypercall可以只借助一次退出发送多个IPI中断。
目前tkernel3已支持该功能，但网络rps发送IPI中断本身无法利用该特性，网络性能在虚拟化场景会降低。
rps using pvipi 测试结果
测试环境, 32核心64G内存, virtio-net 8 queues
rss 中断绑定在24-31核, 观察31核vmexit次数.
1. 1000000pps
100 iperf instances, 10000pps per instance.
disable rps_using_pvipi 68077 vmexit/s
enable rps_using_pvipi 21138 vmexit/s
2. 2000000pps
1000 iperf instances, 2000pps per instance.
disable rps_using_pvipi 40879 vmexit/s
enable rps_using_pvipi 9195 vmexit/s
3. 2000000pps
2000 iperf instances, 1000pps per instance.
disable rps_using_pvipi 24746 vmexit/s
enable rps_using_pvipi 7292 vmexit/s

Rps using pvipi

---

drivers/acpi/apei/hest.c

This timer will cause big schedule latency and network delay
on AMD machine.
Signed-off-by: Hongbo Li <herberthbli@tencent.com>

acpi: disable AMD ghes timer

---

kernel/sched/fair.c

[upstream]
7332dec0 sched/fair: Only immediately migrate tasks due to interrupts
if prev and target CPUs share cache
806486c3 sched/fair: Do not migrate if the prev_cpu is idle
082f764a sched/fair: Do not migrate on wake_affine_weight() if weights
are equal
d8fcb81f sched/fair: Check for idle core in wake_affine
Signed-off-by: yongduan <yongduan@tencent.com>

backport wake affine upstream optimization

---

kernel/sysctl.c
net/core/dev.c

In the virtualization scenario, you can use pvipi to optimize the sending of
IPI interrupts and reduce the number of vmexit.
rps_using_pvipi test
Test guest: 32 core, 64G memory, virtio-net 8 queues, rss interrupt is bound
to 24-31 core. Observe the number of vmexit of 31 cores.
1. 1000000pps
100 iperf instances, 10000pps per instance.
disable rps_using_pvipi  68077 vmexit/s
enable  rps_using_pvipi  21138 vmexit/s
2. 2000000pps
1000 iperf instances, 2000pps per instance.
disable rps_using_pvipi  40879 vmexit/s
enable  rps_using_pvipi  9195  vmexit/s
3. 2000000pps
2000 iperf instances, 1000pps per instance.
disable rps_using_pvipi  24746 vmexit/s
enable  rps_using_pvipi  7292  vmexit/s
Enabling rps_using_pvipi can greatly reduce the number of vmexit.
Signed-off-by: yongduan …

net: rps using pvipi

---

package/arm/generate-rpms.sh
package/arm/repackage/generate-rpms.sh
package/default/generate-rpms.sh
package/default/repackage/generate-rpms.sh

generate-rpms: modify the name of the kernel tag for x86 and arm64
Signed-off-by: Honglin Li <honglinli@tencent.com>

generate-rpms: modify the name of the kernel tag for x86 and arm64

---

net/ipv4/route.c

invalidation
[upstream commit] 5018c59607a511cdee743b629c76206d9c9e6d7b
ipv4: fix race condition between route lookup and invalidation
Jesse and Ido reported the following race condition:
<CPU A, t0> - Received packet A is forwarded and cached dst entry is
taken from the nexthop ('nhc->nhc_rth_input'). Calls skb_dst_set()
<t1> - Given Jesse has busy routers ("ingesting full BGP routing tables
from multiple ISPs"), route is added / deleted and rt_cache_flush() is
called
<CPU B, t2> - Received packet B tries to use the same cached dst entry
from t0, but rt_cache_valid() is no longer true and it is replaced in
rt_cache_route() by the newer one. This calls dst_dev_put() on the
original dst entry which assigns the blackhole netdev to 'dst->dev'
<CPU A, t3> - dst_input(skb) is called on packet …

pv4: fix race condition between route lookup and

---

net/ipv4/netfilter/arp_tables.c
net/ipv4/netfilter/ip_tables.c
net/ipv6/netfilter/ip6_tables.c
net/netfilter/x_tables.c

upsteam: b29c457a6511435960115c0f548c4360d5f4801d
xt_compat_match/target_from_user doesn't check that zeroing the area
to start of next rule won't write past end of allocated ruleset blob.
Remove this code and zero the entire blob beforehand.
Fixes CVE: CVE-2021-22555
Reported-by: syzbot+cfc0247ac173f597aaaa@syzkaller.appspotmail.com
Reported-by: Andy Nguyen <theflow@google.com>
Fixes: 9fa492cdc160c ("[NETFILTER]: x_tables: simplify compat API")
Signed-off-by: Florian Westphal <fw@strlen.de>
Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

netfilter: x_tables: fix compat match/target pad out-of-bound write

---

include/linux/bio.h
include/linux/genhd.h
include/linux/mm_types.h
include/linux/module.h

change place of some reserve words because they are placed under dynamic array
Signed-off-by: Denise Cheng <denisecheng@tencent.com>

kabi: fix kabi reserve place bug

---

fs/overlayfs/namei.c
include/linux/dcache.h

[commit]: 1434a65ea625c51317ccdf06dabf4bd27d20fa10
After calling lookup_one_len_unlocked inside ovl_lookup_positive_unlocked,
the return dentry pointer is used before checking validity, which may represent
error code.
Signed-off-by: caelli <caelli@tencent.com>
Reviewed-by: benbjiang <benbjiang@tencent.com>
Reviewed-by: mengensun <mengensun@tencent.com>

ovl: check return value before using lookup_one_len_unlocked

---

kernel/bpf/syscall.c

'btf' is freed by btf_put() in map_create() if map_check_btf() fails.
However, it is freed again in free_map, which cause use-after-free
in the later process.
Fix this by remove redundant btf_put().
Fixes: c421e6e7b377 ("copy part code from commid id 85d33df357b634649ddbe0a20fd2d0fc5732c3cb to linux 5.4 to fix sockhash map creation fail problem")

bpf: fix double free for btf in map_create()

---

arch/x86/kernel/cpu/amd.c

For AMD EPYC 7K83 64-Core Processor, enable erms/fsrm features to
improve memory copy performance. This is just for specific cpu and
when the features are not transmitted to guest by the host.
Signed-off-by: Peng Hao <flyingpeng@tencent.com>

 cpu/amd: default to enable erms/fsrm features for AMD EPYC 7K83

---

arch/x86/include/asm/cpufeatures.h
arch/x86/lib/memmove_64.S

commit: f444a5ff95dce07cf4353cbb85fc3e785019d430
>From the Intel Optimization Reference Manual:
3.7.6.1 Fast Short REP MOVSB
Beginning with processors based on Ice Lake Client microarchitecture,
REP MOVSB performance of short operations is enhanced. The enhancement
applies to string lengths between 1 and 128 bytes long.  Support for
fast-short REP MOVSB is enumerated by the CPUID feature flag: CPUID
[EAX=7H, ECX=0H).EDX.FAST_SHORT_REP_MOVSB[bit 4] = 1. There is no change
in the REP STOS performance.
Add an X86_FEATURE_FSRM flag for this.
memmove() avoids REP MOVSB for short (< 32 byte) copies. Check FSRM and
use REP MOVSB for short copies on systems that support it.
[ bp: Massage and add comment. ]
Signed-off-by: Tony Luck <tony.luck@intel.com>
Signed-off-by: Borislav Petkov <bp@suse.de> …

x86/cpufeatures: Add support for fast short REP; MOVSB

---

Documentation/admin-guide/kernel-parameters.txt
arch/x86/include/asm/qspinlock.h
arch/x86/kernel/kvm.c
kernel/locking/qspinlock.c

upstream:05eee619ed61c8cd89633954d38c4e5653086845
x86/kvm: Add "nopvspin" parameter to disable PV spinlocks
There are cases where a guest tries to switch spinlocks to bare metal
behavior (e.g. by setting "xen_nopvspin" on XEN platform and
"hv_nopvspin" on HYPER_V).
That feature is missed on KVM, add a new parameter "nopvspin" to disable
PV spinlocks for KVM guest.
The new 'nopvspin' parameter will also replace Xen and Hyper-V specific
parameters in future patches.
Define variable nopvsin as global because it will be used in future
patches as above.
Signed-off-by: Zhenzhong Duan <zhenzhong.duan@oracle.com>
Reviewed-by: Vitaly Kuznetsov <vkuznets@redhat.com>
Cc: Jonathan Corbet <corbet@lwn.net>
Cc: Thomas Gleixner <tglx@linutronix.de>
Cc: Ingo Molnar <mingo@redhat.com>
Cc: Borislav Petkov …

x86/kvm: Add nopvspin parameter to disable PV spinlocks

---

fs/xfs/libxfs/xfs_dir2.h
fs/xfs/libxfs/xfs_dir2_sf.c
fs/xfs/xfs_inode.c

upstream 6da1b4b1ab36d80a3994fd4811c8381de10af604
When overlayfs is running on top of xfs and the user unlinks a file in
the overlay, overlayfs will create a whiteout inode and ask xfs to
"rename" the whiteout file atop the one being unlinked.  If the file
being unlinked loses its one nlink, we then have to put the inode on the
unlinked list.
This requires us to grab the AGI buffer of the whiteout inode to take it
off the unlinked list (which is where whiteouts are created) and to grab
the AGI buffer of the file being deleted.  If the whiteout was created
in a higher numbered AG than the file being deleted, we'll lock the AGIs
in the wrong order and deadlock.
Therefore, grab all the AGI locks we think we'll need ahead of time, and
in order of increasing AG number per the locking rules. …

xfs: fix an ABBA deadlock in xfs_rename

---

arch/alpha/include/uapi/asm/socket.h
arch/mips/include/uapi/asm/socket.h
arch/parisc/include/uapi/asm/socket.h
arch/sparc/include/uapi/asm/socket.h
include/linux/cookie.h
include/linux/sock_diag.h
include/net/net_namespace.h
include/uapi/asm-generic/socket.h
include/uapi/linux/bpf.h
kernel/bpf/cgroup.c
kernel/bpf/reuseport_array.c
net/core/filter.c
net/core/net_namespace.c
net/core/sock.c
net/core/sock_diag.c
net/core/sock_map.c
tools/include/uapi/linux/bpf.h

- [bpf, net: Fix build issue when net ns not configured
](https://github.com/torvalds/linux/commit/5a95cbb80ef8d8f2db29ab10777cd4742e6fc8ec)
- [bpf: Enable retrieval of socket cookie for bind/post-bind hook](https://github.com/torvalds/linux/commit/0e53d9e5e82056555020c47ee0c7a087147be084)
- [bpf, sockmap: Return socket cookie on lookup from syscall
](https://github.com/torvalds/linux/commit/c1cdf65da060a8e047a9f4433306fd6dac1f51a6)
- [bpf, net: Rework cookie generator as per-cpu one
](https://github.com/torvalds/linux/commit/92acdc58ab11af66fcaef485433fde61b5e32fac)
- [net: initialize net->net_cookie at netns setup
](https://github.com/torvalds/linux/commit/3d368ab87cf6681f928de1ddf804d69600671bb2)
- [bpf, sk_msg: Add get socket storage helpers …

backport bpf updates

---

fs/overlayfs/super.c

When umounting overlayfs, it's unnecessary to call sync_filesystem,
because upper fs will make everything work fine.
Signed-off-by: lennychen <lennychen@tencent.com>

fs:ovl: omit sync_filesystem to when sync overlayfs

---

fs/fs_context.c

vfs: fs_context: fix up param length parsing in legacy_parse_param
The "PAGE_SIZE - 2 - size" calculation in legacy_parse_param() is an
unsigned type so a large value of "size" results in a high positive
value instead of a negative value as expected.  Fix this by getting rid
of the subtraction.
Signed-off-by: Jamie Hill-Daniel <jamie@hill-daniel.co.uk>
Signed-off-by: William Liu <willsroot@protonmail.com>
Tested-by: Salvatore Bonaccorso <carnil@debian.org>
Tested-by: Thadeu Lima de Souza Cascardo <cascardo@canonical.com>
Acked-by: Dan Carpenter <dan.carpenter@oracle.com>
Acked-by: Al Viro <viro@zeniv.linux.org.uk>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

backport upstream commit :722d94847de2 which fix CVE-2022-0185

---

kernel/bpf/hashtab.c

Conflict: None
Upstream: 1d4e1eab456e1ee92a94987499b211db05f900ea
Backports following upstream commit:
commit 1d4e1eab456e1ee92a94987499b211db05f900ea
Author: Andrii Nakryiko <andriin@fb.com>
Date:   Tue Jul 28 21:09:12 2020 -0700
bpf: Fix map leak in HASH_OF_MAPS map
Fix HASH_OF_MAPS bug of not putting inner map pointer on bpf_map_elem_update()
operation. This is due to per-cpu extra_elems optimization, which bypassed
free_htab_elem() logic doing proper clean ups. Make sure that inner map is put
properly in optimized case as well.
Fixes: 8c290e60fa2a ("bpf: fix hashmap extra_elems logic")
Signed-off-by: Andrii Nakryiko <andriin@fb.com>
Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
Acked-by: Song Liu <songliubraving@fb.com>
Link: …

bpf: Fix map leak in HASH_OF_MAPS map

---

arch/x86/kernel/kvm.c

For the  mwait-passthrough vm, KVM_FEATURE_PV_UNHALT will not be set.
The current kernel  will use  native_queued_spin_lock_slowpath
instead of __pv_queued_spin_lock_slowpath without disabling virt_spin_lock_key,
that is, native_queued_spin_lock_slowpath always use CAS (compare and swap),
which will result in performance regression.
Signed-off-by: mungerjiang<mungerjiang@tencent.com>

qspinlock: Diable virt_spin_lock for dedicated vm

---

fs/cgroupfs/cgroupfs.h
fs/cgroupfs/mount.c
fs/cgroupfs/sys.c

Add files inside /cgroupfs/sys/devices/system/cpu/, currently sysfs
mounted on /sys/ before cgroupfs is required, we use d_automount
interface to switch from cgroupfs to sysfs.
Signed-off-by: caelli <caelli@tencent.com>
Reviewed-by: Bin Lai <robinlai@tencent.com>

cgroupfs: add files inside sys

---

fs/eventpoll.c

Revert "eventpoll: fix missing wakeup for ovflist in ep_poll_callback"
Revert commit: 72417f224476469fee87e520e656eb197c8842d4
Revert commit: f51fcbb32f68f14d694db359bb101b116662deb1
thoese two commit make nginx slowly like this:
before revert:
--------------
./wrk -t84 -c8400 -d10s -T5s -H "Connection: Close" --latency http://x.x.x.x/hello
Running 10s test @ http://x.x.x.x/hello
84 threads and 8400 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    26.06ms   33.53ms   1.03s    92.66%
Req/Sec   723.03    416.59     9.03k    72.25%
Latency Distribution
50%   18.59ms
75%   31.94ms
90%   52.37ms
99%  141.92ms
592056 requests in 10.10s, 83.00MB read
Socket errors: connect 0, read 253478, write 0, timeout 0
Requests/sec:  58619.13
Transfer/sec:      8.22MB
after revert: …

Revert "epoll: atomically remove wait entry on wake up"

---

drivers/iommu/amd_iommu_init.c

upstream commit:e881dbd5d4a6950c9e2e7623c79d9578949365c9
Currently, the driver only supports lower 32-bit of IOMMU Control register.
However, newer AMD IOMMU specification has extended this register
to 64-bit. Therefore, replace the accessing API with the 64-bit version.
Signed-off-by: Mark Whwu <markwhwu@tencent.com>

iommu/amd: Add support for higher 64-bit IOMMU Control Register

---

mm/vmscan.c

The problem arose after the introduction of the TestClearPageLRU.
After executing SHM_UNLOCK, the mapping for the shared memory area
becomes evictable, and the subsequent pages generated within
the shared area are evictable. In this case, also set the page
to PageLRU.
Signed-off-by: Peng Hao <flyingpeng@tencent.com>

 mm/vmscan: fix shmctl SHM_UNLOCK triggering an warning

---

include/linux/gfp.h
include/linux/mmzone.h
mm/page_alloc.c
mm/swap.c

commit:44042b4498728f4376e84bae1ac8016d146d850b
The per-cpu page allocator (PCP) only stores order-0 pages.  This means
that all THP and "cheap" high-order allocations including SLUB contends on
the zone->lock.  This patch extends the PCP allocator to store THP and
"cheap" high-order pages.  Note that struct per_cpu_pages increases in
size to 256 bytes (4 cache lines) on x86-64.
Note that this is not necessarily a universal performance win because of
how it is implemented.  High-order pages can cause pcp->high to be
exceeded prematurely for lower-orders so for example, a large number of
THP pages being freed could release order-0 pages from the PCP lists.
Hence, much depends on the allocation/free pattern as observed by a single
CPU to determine if caching helps or hurts a particular …

mm/page_alloc: allow high-order pages to be stored on the per-cpu lists

---

block/bio.c
block/blk-cgroup.c
block/blk-mq.c
block/genhd.c
block/partition-generic.c
include/linux/genhd.h

在请求挂死或者queue quiesce时，io_ticks没更新，从proc读到的值不增加，导致ioutil显示为0。这个patch在读取proc时，会更新上次统计到当前时间的io_ticks值，从而达到显示100% util。

修复磁盘挂死显示0% io util问题

---

block/bio.c
block/blk-cgroup.c
block/blk-mq.c
block/genhd.c
block/partition-generic.c
include/linux/genhd.h

在请求挂死或者queue quiesce时，io_ticks没更新，从proc读到的值不增加，导致ioutil显示为0。这个patch在读取proc时，会更新上次统计到当前时间的io_ticks值，从而达到显示100% util。

arm64 修复磁盘挂死显示0% io util问题

---

include/linux/memcontrol.h
mm/memcontrol.c
mm/vmscan.c

开启per-memcg pagecache limit特性：
1.在cgroup v1的版本上，通过memory.limit_in_bytes设置cgroup的内存用量；在cgroup v2版本上，通过memory.max设置cgroup的内存用量。
2.通过memory.pagecache.max_ratio设置pagecache占cgroup内存用量的比例。
立即回收pagecache：
通过echo [5, 100] > memory.pagecache.reclaim_ratio设置pagecache回收比例，并且立即进行一次回收，默认值为5。
查看pagecache用量：
cat memory.pagecache.current
相关sysctl的默认值：
vm.pagecache_limit_retry_times = 5
m.pagecache_limit_global = 0

Pagecache limit linuszeng

---

kernel/cgroup/cgroup-v1.c

upstream commit: 24f6008564183aa120d07c03d9289519c2fe02af
The cgroup release_agent is called with call_usermodehelper.  The function
call_usermodehelper starts the release_agent with a full set fo capabilities.
Therefore require capabilities when setting the release_agaent.
Reported-by: Tabitha Sable <tabitha.c.sable@gmail.com>
Tested-by: Tabitha Sable <tabitha.c.sable@gmail.com>
Fixes: 81a6a5cdd2c5 ("Task Control Groups: automatic userspace notification of idle cgroups")
Cc: stable@vger.kernel.org # v2.6.24+
Signed-off-by: "Eric W. Biederman" <ebiederm@xmission.com>
Signed-off-by: Tejun Heo <tj@kernel.org>

cgroup-v1: Require capabilities to set release_agent

---

include/linux/gfp.h
include/linux/mmzone.h
mm/page_alloc.c
mm/swap.c

Due to unstable results on some machines, revert the backport.
This reverts commit 5312a9ff49b10e9ae70ae7e756f7d28cb22afd22.

Revert "mm/page_alloc: allow high-order pages on the per-cpu lists"

---

fs/cgroupfs/mount.c

when inode created, i_ino default zero, fix by setting
as cgroupfs_entry_t->inum.
Signed-off-by: caelli <caelli@tencent.com>

cgroupfs: initialize i_ino when inode created

---

include/net/netfilter/nf_tables.h
include/net/netfilter/nf_tables_offload.h
net/netfilter/nf_tables_offload.c
net/netfilter/nft_dup_netdev.c
net/netfilter/nft_fwd_netdev.c
net/netfilter/nft_immediate.c

upstream commit: b1a5983f56e371046dcf164f90bfaf704d2b89f6
immediate verdict expression needs to allocate one slot in the flow offload
action array, however, immediate data expression does not need to do so.
fwd and dup expression need to allocate one slot, this is missing.
Add a new offload_action interface to report if this expression needs to
allocate one slot in the flow offload action array.
Fixes: be2861dc36d7 ("netfilter: nft_{fwd,dup}_netdev: add offload support")
Reported-and-tested-by: Nick Gregory <Nick.Gregory@Sophos.com>
Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

netfilter: nf_tables_offload: incorrect flow offload action array size

---

include/net/esp.h
include/net/sock.h
net/core/sock.c
net/ipv4/esp4.c
net/ipv6/esp6.c

upstream commit: ebe48d368e97d007bfeb76fcb065d6cfc4c96645
The maximum message size that can be send is bigger than
the  maximum site that skb_page_frag_refill can allocate.
So it is possible to write beyond the allocated buffer.
Fix this by doing a fallback to COW in that case.
v2:
Avoid get get_order() costs as suggested by Linus Torvalds.
Fixes: cac2661c53f3 ("esp4: Avoid skb_cow_data whenever possible")
Fixes: 03e2a30f6a27 ("esp6: Avoid skb_cow_data whenever possible")
Reported-by: valis <sec@valis.email>
Signed-off-by: Steffen Klassert <steffen.klassert@secunet.com>
Signed-off-by: Vaibhav Rustagi <vaibhavrustagi@google.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

esp: Fix possible buffer overflow in ESP transformation

---

net/ipv4/inet_timewait_sock.c

In the commit
e22ef12b563a ("net: bpf: add BPF_CGROUP_TWSK_CLOSE for tcp timewait sock close")
the new eBPF hook 'BPF_CGROUP_TWSK_CLOSE' is added. However, it doesn't
free 'tw->tw_cgrp_data' properly.
Fix this by call 'cgroup_sk_clone()' while tw sock create and call
'cgroup_sk_free' while it is freed.

net: bpf: fix used-after-free BUG in inet_twsk_kill

---

block/blk-rq-qos.c
include/linux/wait.h
kernel/sched/wait.c

Commit 545fbd0775ba ("rq-qos: fix missed wake-ups in rq_qos_throttle")
tried to fix a problem that a process could be sleeping in rq_qos_wait()
without anyone to wake it up. However the fix is not complete and the
following can still happen:
CPU1 (waiter1)		CPU2 (waiter2)		CPU3 (waker)
rq_qos_wait()		rq_qos_wait()
acquire_inflight_cb() -> fails
acquire_inflight_cb() -> fails
completes IOs, inflight
decreased
prepare_to_wait_exclusive()
prepare_to_wait_exclusive()
has_sleeper = !wq_has_single_sleeper() -> true as there are two sleepers
has_sleeper = !wq_has_single_sleeper() -> true
io_schedule()		  io_schedule()
Deadlock as now there's nobody to wakeup the two waiters. The logic
automatically blocking when there are already sleepers is really subtle
and the only way to make it work …

rq-qos: fix missed wake-ups in rq_qos_throttle try two

---

block/blk-core.c
include/linux/backing-dev.h
include/linux/blkdev.h
include/linux/memcontrol.h
kernel/cgroup/cgroup.c
kernel/sysctl.c
mm/backing-dev.c
mm/memcontrol.c

Backport buffer io qos function in cgroup v1.
Add the ability to bind I/O path to memory cgroup to support seperate buffer I/O read/write's bpf/iops qos function.

Support buffer I/O qos function in cgroup v1

---

fs/proc/Makefile
fs/proc/proc_sysctl.c
fs/proc/sysctl_write_forbid.c
include/linux/proc_fs.h
include/linux/sysctl.h

Users may modify some sysctl parameters intentionally or unintentionally,
which may cause problems such as disconnection of the container network connection.
Therefore, the modification of key sysctl parameters is restricted on the host
and in the container that shares the network namespace with the host.

sysctl: restrict the writting for key parameters

---

drivers/net/ethernet/intel/i40e/i40e_txrx.c
drivers/net/ethernet/intel/iavf/iavf_txrx.c
drivers/vhost/net.c

Uninitialized xdp->data_meta can result in NULL pointer deference in
bpf_xdp_adjust_head(). Therefore, fix it by init it with
xdp_set_data_meta_invalid().

net: bpf: fix uninitialized data_meta in xdp

---

net/core/sock.c

when open gso, tcp Write queues have less overhead, and make some app
run faster.
test of redis-benchmark like follow:
---
echo 1 > /proc/sys/net/core/forced_caps_enabled
get     hset    incr    sadd    set
2781766 737425  2210748 2160010 783656
---
echo 0 > /proc/sys/net/core/forced_caps_enabled
get     hset    incr    sadd    set
2728225 503815  2181630 2127274 507045
see, QPS of hset / set see a huge promote
Signed-off-by:mengensun<mengensun@tencent.com>
Reviewed-by: zhipingdu<zhipingdu@tencent.com>
Reviewed-by: frankjpliu<frankjpliu@tencent.com>

net/tcp: switch to GSO being always on

---

block/blk-cgroup.c
fs/cgroupfs/cgroupfs.h
fs/cgroupfs/mount.c
fs/cgroupfs/proc.c
kernel/cgroup/cpuset.c
kernel/sched/core.c
kernel/sched/cpuacct.c
kernel/sysctl.c
mm/memcontrol.c

currently, /proc/stat displays cpu usage for real cpu,
add support to display cpu usage based on cpuacct,
online file on cgroupfs is changed to display cpu count
minimum of cpuset and cpuacct. sysctl
cgroupfs_stat_show_cpuacct_info is used to start this feature.
Signed-off-by: caelli <caelli@tencent.com>
Reviewed-by: Bin Lai <robinlai@tencent.com>

cgroupfs: support stat based on cpuacct

---

drivers/gpu/drm/hisilicon/hibmc/hibmc_drm_drv.c

upstream commit: c3480301d750bd58bab35994ecf015a4682a17dd
use the drm_fb_helper_remove_conflicting_pci_framebuffer to remove
the framebuffer initialized by fireware/bootloader to avoid resource
conflict.
Signed-off-by: Tian Tao <tiantao6@hisilicon.com>
Acked-by: Thomas Zimmermann <tzimmermann@suse.de>
Signed-off-by: Xinliang Liu <xinliang.liu@linaro.org>
Link: https://patchwork.freedesktop.org/patch/msgid/1582524112-5628-1-git-send-email-tiantao6@hisilicon.com

drm/hisilicon: Fixed pcie resource conflict between drm and firmware

---

block/blk-mq.c

upstream backport: b0d97557ebfc block: fix inflight statistics of part0
cause passthrough req count as inflight, and count as ioutil at reading
diskstats, but not at req completion.
Signed-off-by: samuelliao <samuelliao@tencent.com>

block: dont count passthrough req as inflight

---

mm/memcontrol.c

sameone may mkdir memcg, move some process which will write same
data to disk, then rmdir memcg.
while if do the same thing like up over and over. memcg is bind by
page cache which is recycled slowly, make the memcg tree bigger
and bigger.
then read the numa_stat is so slowly, and costing cpu without
sched point.  while, process like ksoftirqd whill see a loong
sched latency.
so, add a cond_resched to memcg_numa_stat_show
Signed-off-by: mengnesun <mengensun@tencent.com>
Reviewed-by: herberthbli <herberthbli@tencent.com>
Reviewed-by: robinlai <robinlai@tencent.com>

mem: memcontrol: add cond_resched in memcg_numa_stat_show

---

kernel/cgroup/cgroup.c
kernel/cgroup/mbuf.c

Now, mbuf is disabled by default so it can not be used when
some Pods need it. For example, some process have a long sys
with no reason, if mbuf and sli is ready, key stack info may
be recorded. sli can be open during Pods lifecycle, buf mbuf needs
recreate cgroup so as to alloc mbuf memory for it. So, we open mbuf
default.
Default mbuf memory is 2M and supported 512 cgroups, each cgroup has 4K
memory, which is not enough in some case. So just adjust it to 8M.
Signed-off-by: bauerchen <bauerchen@tencent.com>

rue: open mbuf default and set default mbuf size to 8M

---

net/ipv6/ip6_input.c

idev can be NULL, as the surrounding code suggests.
Fixes: 4daf841a2ef3 ("net: ipv6: add skb drop reasons to ip6_rcv_core()")
Signed-off-by: Eric Dumazet <edumazet@google.com>
Cc: Menglong Dong <imagedong@tencent.com>
Cc: Jiang Biao <benbjiang@tencent.com>
Cc: Hao Peng <flyingpeng@tencent.com>
Link: https://lore.kernel.org/r/20220413205653.1178458-1-eric.dumazet@gmail.com
Signed-off-by: Jakub Kicinski <kuba@kernel.org>

ipv6: fix NULL deref in ip6_rcv_core()

---

net/ipv6/tcp_ipv6.c

Looks like the IPv6 version of the patch under Fixes was
a copy/paste of the IPv4 but hit the wrong spot.
It is tcp_v6_rcv() which uses drop_reason as a boolean, and
needs to be protected against reason == 0 before calling free.
tcp_v6_do_rcv() has a pretty straightforward flow.
The resulting warning looks like this:
WARNING: CPU: 1 PID: 0 at net/core/skbuff.c:775
Call Trace:
tcp_v6_rcv (net/ipv6/tcp_ipv6.c:1767)
ip6_protocol_deliver_rcu (net/ipv6/ip6_input.c:438)
ip6_input_finish (include/linux/rcupdate.h:726)
ip6_input (include/linux/netfilter.h:307)
Fixes: f8319dfd1b3b ("net: tcp: reset 'drop_reason' to NOT_SPCIFIED in tcp_v{4,6}_rcv()")
Tested-by: Matthieu Baerts <matthieu.baerts@tessares.net>
Link: https://lore.kernel.org/r/20220520021347.2270207-1-kuba@kernel.org
Signed-off-by: …

tcp_ipv6: set the drop_reason in the right place

---

include/linux/sli.h
kernel/cgroup/sli.c
kernel/sched/core.c

In order to reduce the critical section, we invoke sli_update_tick()
to do sli statistics after release the rq lock. But there is a race
condition that could led the rq_clock warning.
Warning generates like following:
CPU0				CPU1
rq_lock()
update_rq_clock()
rq_unlock()
rq_lock()
sli_update_tick()		load balance
Although, CPU0 had updated the rq_clock(). But CPU1 may concurrently
do the load balance and acquire CPU0's rq lock, and the CPU0's
clock_update_flags would be cleared. It means that caller should
update the rq clock before actually use it. Unfortunately, CPU0
cann't observed it. So the warning was produced by sli when it
invoke rq_clock().
Therefore, we must move the sli_check_longsys() in the front of
rq_unlock().
Signed-off-by: Bin Lai <robinlai@tencent.com>

sli: fix rq_clock warning caused by sli

---

net/core/filter.c

Some error happens while compiling bpf_redirect_peer helper, which
may be caused during code backport.
Fix it by add the missing BPF_F_PEER.

net: bpf: fix compile error in bpf_redirect_peer helper

---

drivers/net/ethernet/broadcom/bnxt/Makefile

bnxt failed to check the exist of xdp_set_data_meta_invalid() and
makes meta_data uninited in xdp_buff.

drivers/net/bnxt: fix xdp initialization error in bnxt_xdp.c

---

net/core/dev.c

The usage of bpf_dispatcher for XDP caused kernel panic, and the reason
has not found. Therefore, disable it for now.

net: bpf: disable the usage of bpf_dispatcher for XDP

---

include/linux/compiler_attributes.h
include/linux/skbuff.h
net/core/dev.c
net/core/skbuff.c

Sometimes, gcc will optimize the function by spliting it to two or
more functions. In this case, kfree_skb_reason() is splited to
kfree_skb_reason and kfree_skb_reason.part.0. However, the
function/tracepoint trace_kfree_skb() in it needs the return address
of kfree_skb_reason().
This split makes the call chains becomes:
kfree_skb_reason() -> kfree_skb_reason.part.0 -> trace_kfree_skb()
which makes the return address that passed to trace_kfree_skb() be
kfree_skb().
Therefore, introduce '__fix_address', which is the combination of
'__noclone' and 'noinline', and apply it to kfree_skb_reason() to
prevent to from being splited or made inline.
(Is it better to simply apply '__noclone oninline' to kfree_skb_reason?
I'm thinking maybe other functions have the same problems)
Meanwhile, wrap …

net: skb: prevent the split of kfree_skb_reason() by gcc

---

net/sched/cls_route.c

upstream: 9ad36309e2719a884f946678e0296be10f0bb4c1
When a route filter is replaced and the old filter has a 0 handle, the old
one won't be removed from the hashtable, while it will still be freed.
The test was there since before commit 1109c00547fc ("net: sched: RCU
cls_route"), when a new filter was not allocated when there was an old one.
The old filter was reused and the reinserting would only be necessary if an
old filter was replaced. That was still wrong for the same case where the
old handle was 0.
Remove the old filter from the list independently from its handle value.
This fixes CVE-2022-2588, also reported as ZDI-CAN-17440.
Reported-by: Zhenpeng Lin <zplin@u.northwestern.edu>
Signed-off-by: Thadeu Lima de Souza Cascardo <cascardo@canonical.com>
Reviewed-by: Kamal Mostafa …

net_sched: cls_route: remove from list when handle is 0

---

package/arm/perf-tlinux.spec
package/default/perf-tools-tlinux.spec

The bash script mkmakefile generates Makefile which includes itself. It leads to dead cycle when build rpm packages.
Signed-off-by: Yushan Zhou <katrinzhou@tencent.com>

perf spec: remove perf obj default

---

package/arm/perf-tlinux.spec
package/default/perf-tools-tlinux.spec

tl2 release system using repackage trick instead of full tl2 env to build kernel and other packages from scratch.
Update the perf tools spec to support build bpftool with perf and kernel tools.
Signed-off-by: Haisu Wang <haisuwang@tencent.com>

package: support repackage bpftool for tl2

---

package/arm/generate-rpms.sh
package/arm/repackage/generate-rpms.sh
package/default/generate-rpms.sh
package/default/repackage/generate-rpms.sh

Modify generate-rpm.sh so that x86/arm can use the same tag.
Signed-off-by: Yushan Zhou <katrinzhou@tencent.com>

generate-rpm.sh: unify package script

---

package/arm/generate-rpms.sh
package/arm/repackage/generate-rpms.sh
package/default/generate-rpms.sh
package/default/repackage/generate-rpms.sh

Tmanager generates tag to build kernel when branch specified. The tag starts with x86, which leads to the build process failing to parse the tag.
Modify the generate-rpms.sh to support building with "x86-*" tags.
Signed-off-by: Yushan Zhou <katrinzhou@tencent.com>

package: support tag startswith x86

---

kernel/sched/debug.c

Kernel-5.4 prohibit user to modify the sched_domain flags bit, but we have to do it to optimize performance in some cases. So we remove the prohibition of sched_domain flags moditication allow user do the better tunning.
Signed-off-by: Bin Lai <robinlai@tencent.com>
Reviewed-by: Bauerchen <bauerchen@tencent.com>

sched/debug: allow user modify sched_domain flags

---

package/arm/kernel-tlinux.spec
package/arm/perf-tlinux.spec
package/default/kernel-tlinux.spec
package/default/perf-tools-tlinux.spec

The perf package include too many duplicated files of bpftool and kernel-tools. Remove/change to the corresponding packages.

Fix the kernel perf package include files

---

drivers/acpi/acpica/utdelete.c

ACPICA commit c11af67d8f7e3d381068ce7771322f2b5324d687
If original_count is 0 in acpi_ut_update_ref_count (), acpi_ut_delete_internal_obj () is invoked for the target object, which is incorrect, because that object has been deleted once already and the memory allocated to store it may have been reclaimed and allocated for a different purpose by the host OS.  Moreover, a confusing debug message following the "Reference Count is already zero, cannot decrement" warning is printed in that case.
To fix this issue, make acpi_ut_update_ref_count () return after finding that original_count is 0 and printing the above warning.
Link: https://github.com/acpica/acpica/commit/c11af67d
Link: https://github.com/acpica/acpica/pull/652
Reported-by: Mark Asselstine <mark.asselstine@windriver.com> …

ACPICA: Utilities: Avoid deleting the same object twice in a row

---

kernel/cgroup/sli.c

The member of member_offset structure should be char pointer and not an array, otherwise it could result in
memlat_member_offset[i].member always be true when we iterate the array. The ARM-GCC can find it and report the error.
Signed-off-by: Bin Lai <robinlai@tencent.com>
Reviewed-by: Munger Jiang <mungerjiang@tencent.com>

sli: fix the compiling error caused by memory access out of range

---

drivers/net/virtio_net.c

Commit a02e8964eaf92 ("virtio-net: ethtool configurable LRO") maps LRO to virtio guest offloading features and allows the administrator to enable and disable those features via ethtool.
This leads to several issues:
- For a device that doesn't support control guest offloads, the "LRO" can't be disabled triggering WARN in dev_disable_lro() when turning off LRO or when enabling forwarding bridging etc.
- For a device that supports control guest offloads, the guest offloads are disabled in cases of bridging, forwarding etc slowing down the traffic.
Fix this by using NETIF_F_GRO_HW instead. Though the spec does not guarantee packets to be re-segmented as the original ones, we can add that to the spec, possibly with a flag for devices to differentiate between GRO and LRO.
Further, we never …

virtio-net: use NETIF_F_GRO_HW instead of NETIF_F_LRO

---

include/net/raw.h
include/net/rawv6.h
net/ipv4/af_inet.c
net/ipv4/raw.c
net/ipv4/raw_diag.c
net/ipv6/af_inet6.c
net/ipv6/raw.c

Upstream commit:0daf07e527095e64ee8927ce297ab626643e9f51 
Upstream commit:af185d8c76333daa877678e0166a7b45e63bf3c4
Using rwlock in networking code is extremely risky. writers can starve if enough readers are constantly grabing the rwlock.
I thought rwlock were at fault and sent this patch:
https://lkml.org/lkml/2022/6/17/272
But Peter and Linus essentially told me rwlock had to be unfair.
We need to get rid of rwlock in networking code.
Without this fix, following script triggers soft lockups:
for i in {1..48}
do
ping -f -n -q 127.0.0.1 &
sleep 0.1
done
Conflicts: rewrite net/ipv4/raw.c net/ipv4/raw_diag.c net/ipv6/raw.c
Fixes: 1da177e4c3f4 ("Linux-2.6.12-rc2")
Signed-off-by: Eric Dumazet <edumazet@google.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
Link: …

raw: convert raw sockets to RCU
