- arch/cris/include/asm/thread_info.h
- arch/frv/include/asm/thread_info.h
- arch/mips/include/asm/thread_info.h
- arch/mn10300/include/asm/thread_info.h
- arch/nios2/include/asm/thread_info.h
- arch/openrisc/include/asm/thread_info.h
- arch/score/include/asm/thread_info.h
> Fixed typo in thread_info.h

- README.md
images use relative paths to avoid breaking images in gitee
> doc: images use relative paths

- fs/proc/bt_stat.c
- fs/proc/stat.c
- include/linux/sched/stat.h
- kernel/fork.c
Signed-off-by: zhiguang peng <zgpeng@tencent.com>
> proc: fix the display error of the processes field in /proc/stat

- package/default/perf-tlinux.spec
spec/x86: modify perf-tlinux.spec
Signed-off-by: Honglin Li <honglinli@tencent.com>
> spec/x86: modify perf-tlinux.spec

- net/ipv4/route.c
there is a compile error in 9db14592151c fix it
Signed-off-by: mengensun<mengensun@tencent.com>
Reviewed-by: kaixuxia<kaixuxia@tencent.com>
> net: fix compile error in 9db14592151c

- drivers/nvme/host/pci.c
- net/ipv4/sysctl_net_ipv4.c
Signed-off-by: Fuhai Wang <fuhaiwang@tencent.com>
> tcp: fix sysctls showed in none init_net netns

- net/ipv4/inet_connection_sock.c
Signed-off-by: Mark Whwu <markwhwu@tencent.com>
> tcp: export sysctl_tcp_pingpong_thresh

- fs/overlayfs/super.c
When umounting overlayfs, it's unnecessary to call sync_filesystem,
because upper fs will make everything work fine.
Signed-off-by: lennychen <lennychen@tencent.com>
> fs:ovl: omit sync_filesystem to when sync overlayfs

- include/net/sock.h
- include/uapi/asm-generic/socket.h
- net/core/sock.c
- net/toa/toa.c
- net/toa/toa.h
toa patch from csig luckyqiu@tencent.com
Signed-off-by: luckyqiu <luckyqiu@tencent.com>
> net: csig toa patch

- drivers/net/virtio_net.c
prevent virtio_net from triggering soft lockup
Signed-off-by: Mark Whwu <markwhwu@tencent.com>
> virtio_net: Add timeout protection to virnet_send_command

- block/genhd.c
- block/partition-generic.c
backport upstream:86d7331299fda7634b11c1b7c911432679d525a5
Signed-off-by: bauerchen <bauerchen@tencent.com>
> fix: update io_ticks in diskstat_show when inflight > 0

- drivers/char/random.c
on some old AMD CPU(eg: older then AMD EPYC 7K62) , rdrand is slowly,
random using rdrand to make the random num more hard to be guessed.
while the randomness is not really affect by rdrand.
so, when user not using random for security case, eg: just geting some
random num, not using it to generate password, using rdrand on old
amd process is so expensive.
so, here add a swith to rdrand, by default using the rdrand, when
closed using tsc, jiffies, and entropy from the fast_pool to emulate
the rdrand
testing on AMD EPYC 7K62 like follow:
---
echo 1 > /proc/sys/kernel/random/tos_use_rdrand
stress-ng --urandom 2 --timeout 10s --times --metrics
bogo ops real time  usr time  sys time   bogo ops/s   bogo ops/s
(secs)    (secs)    (secs)   (real time) (usr+sys time)
16542     10.00      0.00 …
> random: add a switch of using rdrand ins in _extract_crng

- net/toa/toa.c
toa: Support net namespace bypass get toa information
Get net namesacce through PID，and modify it to obtain net namespace through socket.
Get better performance.
> modify toa get net ns from sock from csig

- include/linux/swap.h
- mm/page_alloc.c
- mm/page_io.c
- mm/shmem.c
- mm/swap_state.c
Signed-off-by: Liu Chun <kaicliu@tencent.com>
> swap/mm: free memory and then clear 0

- fs/ext4/mballoc.c
Signed-off-by: Liu Chun <kaicliu@tencent.com>
> fs/ext4: after use, clear the data on the disk

- kernel/cgroup/cgroup.c
- kernel/cgroup/mbuf.c
This reverts commit 22cb10a729724cedbc997b935a046f6eb1a266b9, reversing
changes made to d7c05343985d76ebc9a9910a07f7e8e7261fdb7a.
> Revert "Merge pull request #225 from chenmengc/dev/open_mbuf_def"

- drivers/pci/quirks.c
[desc]:
can use cmdline in grub to:
1). custom set sleep time after device reset.
e.g. pcireset_quirk=timeout,vid1:did1=t1,vid2:did2=t2
this will set t1 second sleep after vid1:did1 device reset and so do vid2:did2
use to solve zixiao gpu reset problem.
2). return 0 directly when device reset.
e.g. pcireset_quirk=noreset,vid1:did1,vid2:did2
this will return 0 when vid1:did1 device reset and so do vid2:did2
use to solve 2080Ti & 3070 GPU reset cause ff problem.
Signed-off-by: leolingli <leolingli@tencent.com>
Signed-off-by: snailzhao <snailzhao@tencent.com>
> kernel: config pci reset quirk by cmdline

- package/default/kernel-tlinux.spec
Build and deliver kernel builtin bpftool
Signed-off-by: Haisu Wang <haisuwang@tencent.com>
> package: enable build bpftool with kernel

- package/arm/perf-tlinux.spec
- package/default/kernel-tlinux.spec
- package/default/perf-tools-tlinux.spec
Build and deliver kernel builtin bpftool in tk4/0009-kabi branch
> build and release bpftool package with kernel 

- package/arm/kernel-tlinux.spec
- package/arm/perf-tlinux.spec
- package/default/kernel-tlinux.spec
- package/default/perf-tools-tlinux.spec
Signed-off-by: Haisu Wang <haisuwang@tencent.com>
Signed-off-by: Yushan Zhou <katrinzhou@tencent.com>
> Fix the kernel perf package

- drivers/scsi/megaraid/megaraid_sas.h
- drivers/scsi/megaraid/megaraid_sas_base.c
- drivers/scsi/megaraid/megaraid_sas_debugfs.c
- drivers/scsi/megaraid/megaraid_sas_fp.c
- drivers/scsi/megaraid/megaraid_sas_fusion.c
- drivers/scsi/megaraid/megaraid_sas_fusion.h
Signed-off-by: mayercheng <mayercheng@tencent.com>
> driver: update megaraid_sas to 07.721.02.00
